version: "3.8"
services:
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=shareit

  server:
    build: ./server
    container_name: server_container
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      #      - TZ=Europe/Moscow
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit

  gateway:
    build: ./gateway
    container_name: gateway_container
    ports:
      - "8080:8080"
    depends_on:
      - db
      - server
    environment:
      #      - TZ=Europe/Moscow
      - SHAREIT_SERVER_URL=http://server:9090

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@root.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  pgadmin-data:


